{% set name = "enterprise-pulsar" %}
{% set version = "3.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/enterprise-pulsar-{{ version }}.tar.gz
  sha256: 5a50bf5c8482b2f1207e7493be7f5b1d5d1bfcfebb5ae1b6133d16ee13644cea

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<3.10
  run:
    - python >=3.6,<3.10
    - ephem >=3.7.6.0
    - healpy >=1.14.0
    - libstempo >=2.4.0
    - numpy >=1.16.3
    - pint-pulsar >=0.8.2
    - scikit-sparse >=0.4.5
    - scipy >=1.2.0

test:
  imports:
    - enterprise
    - enterprise.signals
    - enterprise.pulsar
    - enterprise.constants

about:
  home: https://github.com/nanograv/enterprise
  summary: ENTERPRISE (Enhanced Numerical Toolbox Enabling a Robust PulsaR Inference SuitE)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jellis18
    - Hazboun6
    - paulthebaker
