{% set name = "enterprise-pulsar" %}
{% set version = "3.4.4" %}
{% set python_min = "3.9" %}
{% set python_max = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c95518bb5cf5a96af50d3f1130f1dd565d3a9f54514c8f9f5982b11be3974cf9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }},<={{ python_max }}
    - ephem >=3.7.6.0
    - healpy >=1.14.0
    - numpy >=1.16.3
    - scikit-sparse >=0.4.5
    - scipy >=1.2.0
    - pyarrow >=20.0.0

test:
  requires:
    - python {{ python_min }}
    - pip
    - setuptools
  imports:
    - enterprise
    - enterprise.signals
    - enterprise.pulsar
    - enterprise.constants

about:
  home: https://github.com/nanograv/enterprise
  summary: ENTERPRISE (Enhanced Numerical Toolbox Enabling a Robust PulsaR Inference SuitE)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - meyers-academic
    - AaronDJohnson
    - jellis18
    - Hazboun6
    - paulthebaker
